#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long barLengths[7];
int i = 0;
int colorCheck = 0;
bool blackFlag = true;
bool whiteFlag = false;


void record(){
	barLengths[i] = getMotorEncoder(leftMotor);
	resetMotorEncoder(leftMotor);
	i++;
}


task main()	{

	resetMotorEncoder(leftMotor);

	setMotorTarget(leftMotor, 635, 50);
	setMotorTarget(rightMotor, 635, 50);
	waitUntilMotorStop(leftMotor);
	resetMotorEncoder(leftMotor);

	setMotorSpeed(leftMotor, 70);
	setMotorSpeed(rightMotor, 70);
	waitUntil(getColorReflected(colorSensor) < 30);

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

	resetMotorEncoder(leftMotor);

		setMotorSpeed(leftMotor, 30);
	setMotorSpeed(rightMotor, 30);

	while(i<7){

		colorCheck = getColorReflected(colorSensor);

		if (colorCheck <30){
			if (blackFlag == false){
				blackFlag = true;
				whiteFlag = false;
				record();
			}
		}

		if (colorCheck >70){as
			if (whiteFlag == false){
				blackFlag = false;
				whiteFlag = true;
				record();
			}
		}
	}

	datalogClear();
	datalogDataGroupStart();
	for (int k = 0;k<7;k++){
			datalogAddValue(k,barLengths[k]);
	}
	datalogDataGroupEnd();
}
