#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int orientation = 0;
int angle = 0;


void checkDirection(){
//find what direction we are facing
	angle = getGyroHeading(gyroSensor);
	if(getGyroHeading(gyroSensor)<= 45 && getGyroHeading(gyroSensor)>-45){
		orientation = 0;
	}
	else if(getGyroHeading(gyroSensor)> 45 && getGyroHeading(gyroSensor)<= 135){
		orientation = 3;
	}
	else if(getGyroHeading(gyroSensor)> 135 || getGyroHeading(gyroSensor)<= -135){
		orientation = 2;
	}
	else if(getGyroHeading(gyroSensor)> -135 && getGyroHeading(gyroSensor)<= -45){
		orientation = 1;
	}
}


task main()
{
	resetGyro(gyroSensor);
	wait1Msec(100);
	while(true){
		checkDirection();
		displayTextLine(1,"Angle: %d",angle);
    displayTextLine(3,"Orientation: %d",orientation);
	}



}
