#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int gridLength = 10;

void turnRight(){
	int initialPos  = getGyroHeading(gyroSensor);
	setMotorSpeed(leftMotor,10);
	setMotorSpeed(rightMotor,-10);
	waitUntil(getGyroHeading(gyroSensor) >= initialPos + 90);
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}
void turnLeft(){
	int initialPos  = getGyroHeading(gyroSensor);
	setMotorSpeed(leftMotor,-10);
	setMotorSpeed(rightMotor,10
	);
	waitUntil(getGyroHeading(gyroSensor) <= initialPos - 90);
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}


task main()
{
	resetGyro(gyroSensor);
	for(int i = 0; i<5;i++){
		turnLeft();
		turnRight();
	}

}
