#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//0 = no wall, 1 = wall


//177 x 127
const int cellSizeX = 80/8;
const int cellSizeY = 60/6;
struct mazeCell{
	int northWall;
	int eastWall;
	int southWall;
	int westWall;
	bool visited;
}

struct mazeCell Maze[6][8];

void mazeInit();
void buildOuterWalls();
void simulateMaze();

task main()
{
	mazeInit();
	buildOuterWalls();

}



void simulateMaze(){
	//check each item in the array with each position, if 1 draw line
	int cellX = 0;
	int cellY = 0;
	for(int row = 0; row < 6; row++){
		for( int column = 0; column < 8; column++){
			if (Maze[row][column].northWall == 1){
				drawLine(row, cellSizeY + row, row + cellSizeX, cellSizeY);

			}
			if (Maze[row][column].eastWall == 1){
				//draw lines
			}
			if (Maze[row][column].southWall == 1){
				//draw line
			}
			if (Maze[row][column].westWall == 1){
				//draw line
			}
		}
	}
}





void buildOuterWalls()
{
	//in memory
	Maze[0][0].westWall = 1;
	for(int row = 0; row <6;row++){
		Maze[row][0].westWall = 1;
		Maze[row][7].eastWall = 1;
	}
	for(int column = 0; column <6;column++){
		Maze[0][column].southWall = 1;
		Maze[5][column].northWall = 1;
	}

}

void mazeInit()
{
	for(int row = 0; row < 6; row++){
		for( int column = 0; column < 8; column++){
			Maze[row][column].northWall = 0;		//0 = no wall, 1 = wall
			Maze[row][column].eastWall = 0;
			Maze[row][column].southWall = 0;
			Maze[row][column].westWall = 0;
			Maze[row][column].visited = false;
		}
	}
}
