#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int dataPoints = 7;
long barLengths[dataPoints];
int i = 0;
int colorCheck = 0;
bool blackFlag = true;
bool whiteFlag = false;

void record(){
	barLengths[i] = getMotorEncoder(leftMotor);
	resetMotorEncoder(leftMotor);
}


void decodeData(){
	float threshold = (barLengths[0]+barLengths[1])/2;

	short binVal[4];

	int j = 0;
	for (int i = 0;i<dataPoints;i+=2){
		if (barLengths[i]>threshold){
			binVal[j] = 1;
		}
		else{
			binVal[j] = 0;
		}
		j++;
	}
	int answer = 0;
	for(int k = 0; k<4; k++){
		if (binVal[k] == 1){
			answer = answer + pow(2,k);
		}
	}

	//answer = binVal[0]^0 + binVal[1]^1 + binVal[2]^2 + binVal[3]^3;
  displayCenteredBigTextLine(5,"%d", answer);

}


task main()	{

	int aaaaaa = getColorReflected(colorSensor);

	resetMotorEncoder(leftMotor);

	setMotorSpeed(leftMotor,	30);
	setMotorSpeed(rightMotor, 30);
	wait1Msec(3000);
	resetMotorEncoder(leftMotor);

	while(true) {

		if (getColorReflected(colorSensor) < 50){
				resetMotorEncoder(leftMotor);
				break;
			}
		}

	//waitUntil(getColorReflected(colorSensor) < 20);

//setMotorSpeed(leftMotor, 0);
	//setMotorSpeed(rightMotor, 0);

	//waitUntilMotorStop(leftMotor);
	///wait1Msec(1000);

	//resetMotorEncoder(leftMotor);

	while(i<dataPoints){

		colorCheck = getColorReflected(colorSensor);

		if (colorCheck <45){
			if (blackFlag == false){
				blackFlag = true;
				whiteFlag = false;
				record();
				i++;
			}
		}

		if (colorCheck >55){
			if (whiteFlag == false){
				blackFlag = false;
				whiteFlag = true;
				record();
				i++;
			}
		}
	}

	datalogClear();
	datalogDataGroupStart();
	for (int k = 0;k<dataPoints;k++){
			datalogAddValue(k,barLengths[k]);
	}
	datalogDataGroupEnd();

	decodeData();

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	wait1Msec(2000);


}
