#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
These are functions used in calibration of the robot to detect the side of the line
it sweeps left and right until it finds the line and detects the side it is on
*/


task stopAndResetMotors(){
//Stops motors and resets the encoders
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
}


bool calibration(){
//returns true if line is on Robot's right, false if line is on left

	startTask(stopAndResetMotors);
	int encoderTarget = 90;
	displayCenteredTextLine(3, "Calibrating...");
	setLEDColor(ledOrange);

	while(true){
		setMotorSpeed(rightMotor, 5); //rotate left
		setMotorSpeed(leftMotor, -5);

		waitUntil(getColorReflected(colorSensor) == colorBlack || abs(getMotorEncoder(rightMotor))>= encoderTarget);
		startTask(stopAndResetMotors);

		if (getColorReflected(colorSensor) == colorBlack){
			return false; //line is on left
		}

		setMotorSpeed(rightMotor, -5); //rotate right
		setMotorSpeed(leftMotor, 5);

		waitUntil(getColorReflected(colorSensor) == colorBlack || abs(getMotorEncoder(rightMotor))>= 2*encoderTarget);
		startTask(stopAndResetMotors);

		if (getColorReflected(colorSensor) == colorBlack){
			return true; //line is on right
		}
		else {
				startTask(stopAndResetMotors);
				setMotorSpeed(rightMotor, 5); //rotate left
				setMotorSpeed(leftMotor, -5);
				waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
				startTask(stopAndResetMotors);
				encoderTarget += 90;
				if (encoderTarget >= 360){
					startTask(stopAndResetMotors);
					return true; //assume line is on left
				}
		}
	}
	return true;
}

task main(){

	if (calibration() == true){
		setLEDColor(ledGreen);
		displayCenteredTextLine(3, "The Line is on My Right");
	}
	else {
		setLEDColor(ledRed);
		displayCenteredTextLine(3, "The Line is on My Left");
	}
}
