#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variables
int desiredVal = 70;
float errorFactor = 1;
float errorVal= 0;



task driftRight(){
	setMotorSpeed(leftMotor, 10);
	setMotorSpeed(rightMotor, 0);
}

task driftLeft(){
	setMotorSpeed(rightMotor, 10);
	setMotorSpeed(leftMotor, 0);
}

task pickUp() {
	while(getUSDistance(sonarSensor) > 3){
			setMotorSpeed(leftMotor, 10);
			setMotorSpeed(rightMotor, 10);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setMotorTarget(armMotor, -160, 60);
	waitUntilMotorStop(armMotor);

}

task drive(){
	setMotorSpeed(leftMotor,-errorFactor*errorVal);
	setMotorSpeed(rightMotor,errorFactor*errorVal);
}


task main(){
	/*while(true){
		startTask(pickUp);
		waitUntil(getMotorEncoder(armMotor) != 0);
		//setMotorTarget(leftMotor,4, 30);
		//setMotorTarget(rightMotor,480, 30);
		waitUntilMotorStop(leftMotor);*/
		while(true){
			//errorVal = desiredVal - getColorReflected(colorSensor);
			//startTask(drive);

			while(getColorReflected(colorSensor)<20){
				setMotorSpeed(rightMotor, 10);
				setMotorSpeed(leftMotor, -10);
			}
			while(getColorReflected(colorSensor)>40){
				setMotorSpeed(rightMotor, 0);
				setMotorSpeed(leftMotor, 10);
					}
			while(getColorReflected(colorSensor)<45 && getColorReflected(colorSensor)>15){
					setMotorSpeed(rightMotor, 10)
					setMotorSpeed(leftMotor, 10);
				}
			/*startTask(driftRight);
			while(getColorReflected(colorSensor) < 36){
				startTask(driftLeft);
			}*/
		//}
	}
}
