#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variables


int targetColor = 15;
int allignmentVal = 1;
int rightMtrSpd = 0;
int leftMtrSpd = 10;
const int speed = 25;
const float wheelDiameter = 0.056;
int pickupDistance = 480;
int armAngle = 45;
int armSpeed = 30;

int red;
int blue;
int green;





void pickUp() {

	//find box to pickup and drive into postion to begin tracking
	setMotorTarget(armMotor, armAngle, armSpeed);
	waitUntilMotorStop(armMotor);
	while(getUSDistance(sonarSensor) > 3){
		setMotorSpeed(leftMotor, speed);
		setMotorSpeed(rightMotor, speed);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setMotorTarget(armMotor, -armAngle, armSpeed);
	//waitUntilMotorStop(armMotor);
	setMotorTarget(leftMotor,pickupDistance, speed);//480
	setMotorTarget(rightMotor,pickupDistance, speed);
	waitUntilMotorStop(leftMotor);

}

void stopAndResetMotors(){
	//this function is used to halt motor operation and reset for many cases
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}


void putDown() {
	stopAndResetMotors();
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setMotorTarget(armMotor, armAngle, armSpeed);
	//waitUntilMotorStop(armMotor);

	setMotorTarget(leftMotor,-pickupDistance, speed);
	setMotorTarget(rightMotor,-pickupDistance, speed);
	waitUntilMotorStop(leftMotor);
	setMotorTarget(armMotor, -armAngle, armSpeed);
}


bool calibration(){
//returns true if line is on Robot's right, false if line is on left
	int encoderTarget = 90;
	int calibrationSpeed = 5;

	stopAndResetMotors();

	displayCenteredTextLine(3, "Calibrating...");
	setLEDColor(ledOrange);

	while(true){
		setMotorSpeed(rightMotor, calibrationSpeed); //rotate left
		setMotorSpeed(leftMotor, -calibrationSpeed);

		//rotate until either the color is found or limit reached
		waitUntil((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)  || abs(getMotorEncoder(rightMotor))>= encoderTarget);
		stopAndResetMotors();

		//if the target color has been found, rotate back straight and finish calibration
		if ((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)){
			setMotorSpeed(rightMotor, -calibrationSpeed); //rotate right
			setMotorSpeed(leftMotor, calibrationSpeed);
			waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
			stopAndResetMotors();
			return false; //line is on left
		}

		setMotorSpeed(rightMotor, -calibrationSpeed); //rotate right
		setMotorSpeed(leftMotor, calibrationSpeed);

		//rotate back the opposite direction until color is found or limit reached
		waitUntil((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)  || abs(getMotorEncoder(rightMotor))>= 2*encoderTarget); //Error <= 15 && Error >=  -15
		stopAndResetMotors();

		//if the target color has been found, rotate back straight and finish calibration
		if ((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)){
			setMotorSpeed(rightMotor, calibrationSpeed); //rotate left
			setMotorSpeed(leftMotor, -calibrationSpeed);
			waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
			stopAndResetMotors();
			return true; //line is on right
		}
		else {
			//if no color was found on first sweep, reset to centre and widen range
				stopAndResetMotors();
				setMotorSpeed(rightMotor, calibrationSpeed); //rotate left
				setMotorSpeed(leftMotor, -calibrationSpeed);
				waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
				stopAndResetMotors();
				encoderTarget += 90;

				if (encoderTarget >= 360){
					stopAndResetMotors();
					return true; //assume line is on left
				}
		}
	}
	return true;
}


bool fork () {
	//calculate the target distance from the start point and set an encoder end condition based on that value
	//(given an error of about 50 encoder counts)
	short lengthOfTrack = 1.42;
	int encoderError = 800;
	short encoderForkDistance = lengthOfTrack/(PI*wheelDiameter)*360 + encoderError;

	if (abs(getMotorEncoder(leftMotor)) > encoderForkDistance || abs(getMotorEncoder(rightMotor)) > encoderForkDistance){
		return true;
	}
	else{
		return false;
	}
}

void deliverySuccess(){
	int j = 0;
	for (j = 0; j<3; j++)
  {
    displayCenteredBigTextLine(4, "Delivery Success!");
		wait1Msec(1000);
		eraseDisplay();
		wait1Msec(1000);
  }

}








task main(){
	pickUp();		//comment out for no box to pickup

//---Calibration---//
//comment out below if/else statment for no calibration. uncomment next spot
	if (calibration() == true){ //calibrate says line is on right, set motor control variables accordingly
		setLEDColor(ledGreen);
		displayCenteredTextLine(3, "The Line is on My Right");
		allignmentVal = 1;
		rightMtrSpd = 0;
		leftMtrSpd = 10;
	}
	else {											//calibrate says line is on left, set motor control variables accordingly
		setLEDColor(ledRed);
		displayCenteredTextLine(3, "The Line is on My Left");
		allignmentVal = -1;
		rightMtrSpd = 10;
		leftMtrSpd = 0;
	}
	stopAndResetMotors();

//---LineTracking---//
	getColorRGB(colorSensor, red, blue, green);

	while((red / (blue+1) > 4 && red / (green+1) > 4) == false){ //while not red

		if(red < targetColor - 5 && blue < targetColor - 5){ //to black turn away from line
		//When Line is on right -> this is for left turns
		//When Line is on left -> this is for right turns
			setMotorSpeed(rightMotor, speed*allignmentVal);
			setMotorSpeed(leftMotor, -speed*allignmentVal);
			getColorRGB(colorSensor, red, blue, green);
		}
		else if(red > targetColor + 5 && blue > targetColor + 5){ //too white
		//When Line is on right -> this is for right turns
		//When Line is on left -> this is for left turns
			setMotorSpeed(rightMotor, rightMtrSpd);
			setMotorSpeed(leftMotor, leftMtrSpd);
			getColorRGB(colorSensor, red, blue, green);
				}
		else if(red > targetColor -5 && red < targetColor + 5 && blue > targetColor - 5 && blue < targetColor + 5 ){ //on the edge
		//go straight, dont turn
			setMotorSpeed(rightMotor, speed);
			setMotorSpeed(leftMotor, speed);
			getColorRGB(colorSensor, red, blue, green);
			}
		getColorRGB(colorSensor, red, blue, green);


		/*
		this section is to stop when at the fork in the road and place the box for challenge 5
		comment out below function if not needed
		*/
			//if (fork()){
			//	break;
			//}

	}


	putDown();	//comment out for no box to putdown

	deliverySuccess();

}
