#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variables
int desiredVal = 70;
float errorFactor = 1;
float errorVal= 0;
int allignmentVal;
int targetColor = 30;
int rightMtrSpd;
int leftMtrSpd;

int red;
int blue;
int green;




task driftRight(){
	setMotorSpeed(leftMotor, 10);
	setMotorSpeed(rightMotor, 0);
}

task driftLeft(){
	setMotorSpeed(rightMotor, 10);
	setMotorSpeed(leftMotor, 0);
}

void pickUp() {
	setMotorTarget(armMotor, 90, 30);
	waitUntilMotorStop(armMotor);
	while(getUSDistance(sonarSensor) > 3){
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
	}
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setMotorTarget(armMotor, -80, 30);
	//waitUntilMotorStop(armMotor);
	setMotorTarget(leftMotor,480, 10);
	setMotorTarget(rightMotor,480, 10);
	waitUntilMotorStop(leftMotor);

}

void putDown() {
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	setMotorTarget(armMotor, 90, 30);
	waitUntilMotorStop(armMotor);

	setMotorTarget(leftMotor,-480, 10);
	setMotorTarget(rightMotor,-480, 10);
	waitUntilMotorStop(leftMotor);
	setMotorTarget(armMotor, -80, 30);
}

task stopAndResetMotors(){
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
}

bool calibration(){
//returns true if line is on Robot's right, false if line is on left

	startTask(stopAndResetMotors);
	int encoderTarget = 90;
	displayCenteredTextLine(3, "Calibrating...");
	setLEDColor(ledOrange);

	while(true){
		setMotorSpeed(rightMotor, 5); //rotate left
		setMotorSpeed(leftMotor, -5);

		waitUntil((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)  || abs(getMotorEncoder(rightMotor))>= encoderTarget);
		startTask(stopAndResetMotors);

		if ((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)){
			setMotorSpeed(rightMotor, -5); //rotate right
			setMotorSpeed(leftMotor, 5);
			waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
			startTask(stopAndResetMotors);
			return false; //line is on left
		}

		setMotorSpeed(rightMotor, -5); //rotate right
		setMotorSpeed(leftMotor, 5);

		waitUntil((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)  || abs(getMotorEncoder(rightMotor))>= 2*encoderTarget); //Error <= 15 && Error >=  -15
		startTask(stopAndResetMotors);

		if ((getColorReflected(colorSensor) <= targetColor + 10 && getColorReflected(colorSensor) >= targetColor - 10)){
			setMotorSpeed(rightMotor, 5); //rotate left
			setMotorSpeed(leftMotor, -5);
			waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
			startTask(stopAndResetMotors);
			return true; //line is on right
		}
		else {
				startTask(stopAndResetMotors);
				setMotorSpeed(rightMotor, 5); //rotate left
				setMotorSpeed(leftMotor, -5);
				waitUntil(abs(getMotorEncoder(rightMotor))>= encoderTarget);
				startTask(stopAndResetMotors);
				encoderTarget += 90;
				if (encoderTarget >= 360){
					startTask(stopAndResetMotors);
					return true; //assume line is on left
				}
		}
	}
	return true;
}

task main(){

pickUp();

	if (calibration() == true){
		setLEDColor(ledGreen);
		displayCenteredTextLine(3, "The Line is on My Right");
		allignmentVal = 1;
		rightMtrSpd = 0;
		leftMtrSpd = 10;

	}
	else {
		setLEDColor(ledRed);
		displayCenteredTextLine(3, "The Line is on My Left");
		allignmentVal = -1;
		rightMtrSpd = 10;
		leftMtrSpd = 0;
	}

	getColorRawRGB(colorSensor, red, blue, green);

	while((red / (blue+1) > 2 && red / (green+1) > 2) == false){
		getColorRawRGB(colorSensor, red, blue, green);
		while(getColorReflected(colorSensor)<targetColor-10){ //When Line is on right -> this is for left turns
			setMotorSpeed(rightMotor, 10*allignmentVal);				//When Line is on left -> this is for right turns
			setMotorSpeed(leftMotor, -10*allignmentVal);
		}
		while(getColorReflected(colorSensor)>targetColor+10){
			setMotorSpeed(rightMotor, rightMtrSpd);
			setMotorSpeed(leftMotor, leftMtrSpd);
				}
		while(getColorReflected(colorSensor)<targetColor+15 && getColorReflected(colorSensor)> targetColor -15){
			setMotorSpeed(rightMotor, 10);
			setMotorSpeed(leftMotor, 10);
			}
	}
	putDown();

}
