#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float pConst = 1.5;
const float iConst = 0.0000005;
const float dConst = 4;
const float targetColor = 30;
const float straightDrive = 15;

float pValue;
float iValue;
float dValue;

float Error;
float lastError;
float integral = 0;
float derivative;
float pidDrive;

bool integralInitiation = false;

task main() {
	while (true){

		Error = getColorReflected(colorSensor) - targetColor;

		if (Error == 0){
			integralInitiation = true;
		}

		if (integralInitiation == true && Error < 20) {
			integral += Error;
		}

		derivative = Error - lastError;
		lastError = Error;

		pValue = pConst*Error;

		if (pValue > 25) {
			pValue = 25;
		}
		else if (pValue < -25) {
			pValue = -25;
		}

		iValue = iConst*integral;
		dValue = dConst*derivative;

		pidDrive = pValue +iValue + dValue;

		setMotorSpeed(rightMotor, straightDrive - pidDrive);
		setMotorSpeed(leftMotor, straightDrive + pidDrive);
 	}
}
